name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build with Next.js
        run: |
          echo "Starting Next.js build process..."
          yarn build
          echo "Build completed. Checking output directory..."
          if [ -d "./out" ]; then
            echo "✅ out directory exists"
            ls -la ./out/
          else
            echo "❌ out directory not found"
            echo "Available directories:"
            ls -la ./
            echo "Trying alternative build methods..."
            rm -rf .next out
            NODE_ENV=production yarn next build || echo "Alternative build failed"
            ls -la ./
          fi
        env:
          NEXT_PUBLIC_AIRTABLE_PAT: ${{ secrets.NEXT_PUBLIC_AIRTABLE_PAT }}
          NEXT_PUBLIC_AIRTABLE_BASE: ${{ secrets.NEXT_PUBLIC_AIRTABLE_BASE }}
          NEXT_PUBLIC_AIRTABLE_TABLE: ${{ secrets.NEXT_PUBLIC_AIRTABLE_TABLE }}
        
      - name: Check if out directory exists before upload
        run: |
          if [ ! -d "./out" ]; then
            echo "❌ Error: out directory does not exist"
            echo "Current directory contents:"
            ls -la ./
            exit 1
          fi
          echo "✅ out directory confirmed, proceeding with upload"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4